### ISSUE TITLE
Error while running aegea-build-image-for-mission

### ISSUE THREAD

**Issue by Bek** [kislyuk/aegea#16]
I tried running docker-example mission, but getting the following error:

<pre><code>
Traceback (most recent call last):
  File "/usr/local/bin/aegea", line 23, in <module>
    aegea.main()
  File "/Library/Python/2.7/site-packages/aegea/__init__.py", line 80, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Library/Python/2.7/site-packages/aegea/build_docker_image.py", line 78, in build_docker_image
    ensure_ecr_repo(args.name, read_access=args.read_access)
  File "/Library/Python/2.7/site-packages/aegea/build_docker_image.py", line 70, in ensure_ecr_repo
    clients.ecr.set_repository_policy(repositoryName=name, policyText=str(policy))
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 544, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the SetRepositoryPolicy operation: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Invalid repository policy provided'
Traceback (most recent call last):
  File "/usr/local/bin/aegea-build-image-for-mission", line 42, in <module>
    env=dict(os.environ, AEGEA_CONFIG_FILE=os.path.join(mission_wd, "config.yml"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'aegea', u'build_docker_image', 'dex', u'--tags', u'AegeaMission=docker-example']' returned non-zero exit status 1
</code></pre>
Is PolicyText something I should provide to boto?

**Comment by kislyuk** [comment]
Sorry, this looks like a bug within aegea. No, you should not be required to provide `PolicyText` explicitly. Looking into this, fix coming asap.

**Comment by kislyuk** [comment]
Fixed in v1.9.11. Please upgrade and try again.
